CREATE TABLE IF NOT EXISTS User (
  user_id INTEGER PRIMARY KEY NOT NULL UNIQUE,
  name NUMERIC NOT NULL,
  email TEXT NOT NUll
);

CREATE  TABLE IF NOT EXISTS Production (
  prod_id INTEGER PRIMARY KEY NOT NULL UNIQUE ,
);

CREATE  TABLE IF NOT EXISTS Performance (
  perf_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
);