const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  // These credentials were autogenerated by Ethereal
  // Go to ethereal website to see the messages sent from the server
  host: "smtp.ethereal.email",
  port: 587,
  auth: {
    user: "wilfred.goyette@ethereal.email",
    pass: "Hj1T9CeqnTBQ1zm8dt"
  }
});

async function sendForgotPassword(email, reset_link) {
  const message = {
    from: "noreply@tick.et",
    to: email,
    subject: "Reset password",
    text: "Please use the link below to reset your password. The link will expire in 10 minutes.\nReset link: " + reset_link,
    html: "<p>Please use the link below to reset your password. The link will expire in 10 minutes.<br />Reset link: <a href=\"" + reset_link + "\">" + reset_link + "</a></p>"
  };
  await transporter.sendMail(message);
}

exports.sendForgotPassword = sendForgotPassword;